site_name: RISK Documentation
site_url: https://github.com/riskportal/risk
repo_url: https://github.com/riskportal/risk-docs
repo_name: risk-docs
theme:
  name: material
  custom_dir: docs/stylesheets
  logo: images/risk_logo.png
  favicon: images/risk_logo.ico
  features:
    - navigation.top
    - navigation.expand
    - content.code.copy
    - toc.integrate
  palette:
    - scheme: default
      primary: custom
      accent: light blue
    - scheme: slate
      primary: custom
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
nav:
  - Home: index.md
  - Getting Started:
      - 0. Introduction: 0_introduction.md
      - 1. Installation: 1_installation.md
  - Core Features:
      - 2. Network Input: 2_network_input.md
      - 3. Annotation Input: 3_annotation_input.md
      - 4. Clustering: 4_clustering.md
      - 5. Statistical Methods: 5_statistical_methods.md
      - 6. Analyzing Results: 6_analyzing_results.md
      - 7. Visualization: 7_visualization.md
      - 8. Analysis Parameters: 8_parameters.md
  - Full Tutorial (HTML): tutorial.html
  - Download Tutorial Notebook & Data: tutorial.zip
  - Interactive Quickstart (Binder): https://mybinder.org/v2/gh/riskportal/risk-docs/HEAD?filepath=notebooks/quickstart.ipynb
extra_css:
  - stylesheets/extra.css
